//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLaDOS.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLaDOS.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Caption_Error {
            get {
                return ResourceManager.GetString("Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string Caption_Information {
            get {
                return ResourceManager.GetString("Caption_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string Caption_Worning {
            get {
                return ResourceManager.GetString("Caption_Worning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告，当前操作不可逆，是否确认删除？ 的本地化字符串。
        /// </summary>
        internal static string Meg_Delete_Confirm {
            get {
                return ResourceManager.GetString("Meg_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 捕获到程序异常 的本地化字符串。
        /// </summary>
        internal static string Msg_Catch_Exception {
            get {
                return ResourceManager.GetString("Msg_Catch_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该功能已经存在菜单中，请勿重复添加！ 的本地化字符串。
        /// </summary>
        internal static string Msg_Function_Already_Exist_In_Menu {
            get {
                return ResourceManager.GetString("Msg_Function_Already_Exist_In_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你好，世界！ 的本地化字符串。
        /// </summary>
        internal static string Msg_Hello_World {
            get {
                return ResourceManager.GetString("Msg_Hello_World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败！ 的本地化字符串。
        /// </summary>
        internal static string Msg_Operation_Failed {
            get {
                return ResourceManager.GetString("Msg_Operation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功！ 的本地化字符串。
        /// </summary>
        internal static string Msg_Operation_Succeeded {
            get {
                return ResourceManager.GetString("Msg_Operation_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该数据已存在数据库，请不要重复写入！ 的本地化字符串。
        /// </summary>
        internal static string Msg_PK_Already_Exist {
            get {
                return ResourceManager.GetString("Msg_PK_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的类型不存在 的本地化字符串。
        /// </summary>
        internal static string Msg_TargetClass_IsNot_Exist {
            get {
                return ResourceManager.GetString("Msg_TargetClass_IsNot_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的类型无法识别为Form 的本地化字符串。
        /// </summary>
        internal static string Msg_TargetClass_IsNot_Form {
            get {
                return ResourceManager.GetString("Msg_TargetClass_IsNot_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不存在或密码错误！ 的本地化字符串。
        /// </summary>
        internal static string Msg_UserOrPassword_Error {
            get {
                return ResourceManager.GetString("Msg_UserOrPassword_Error", resourceCulture);
            }
        }
    }
}
