//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLaDOS.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLaDOS.Properties.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 delete from Function where FunctionName = ? 的本地化字符串。
        /// </summary>
        internal static string SQL_Delete_Function_Ver_001 {
            get {
                return ResourceManager.GetString("SQL_Delete_Function_Ver_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from FunctionMenu where UserGroupName = ? 的本地化字符串。
        /// </summary>
        internal static string SQL_Delete_FunctionMenu_Ver_001 {
            get {
                return ResourceManager.GetString("SQL_Delete_FunctionMenu_Ver_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 insert into Function (FunctionName, FunctionDesc, FunctionType, AssemblyFile, AssemblyName) values (?, ?, ?, ?, ?) 的本地化字符串。
        /// </summary>
        internal static string SQL_Insert_Function_Ver_001 {
            get {
                return ResourceManager.GetString("SQL_Insert_Function_Ver_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 insert into FunctionMenu (FunctionName, FunctionIndex, ParentName, UserGroupName) values (?, ?, ?, ?) 的本地化字符串。
        /// </summary>
        internal static string SQL_Insert_FunctionMenu_Ver_001 {
            get {
                return ResourceManager.GetString("SQL_Insert_FunctionMenu_Ver_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select * from Function where FunctionName = ? 的本地化字符串。
        /// </summary>
        internal static string SQL_Select_Function_Ver_001 {
            get {
                return ResourceManager.GetString("SQL_Select_Function_Ver_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select * from Function where FunctionType = ? or ? is null 的本地化字符串。
        /// </summary>
        internal static string SQL_Select_FunctionList_Ver_001 {
            get {
                return ResourceManager.GetString("SQL_Select_FunctionList_Ver_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT a.FunctionName, b.FunctionDesc, a.ParentName, b.FunctionType, b.AssemblyFile, b.AssemblyName, a.FunctionIndex
        ///FROM FunctionMenu a, Function b
        ///WHERE a.UserGroupName = ? AND a.FunctionName = b.FunctionName
        ///ORDER BY a.ParentName ASC, a.FunctionIndex ASC; 的本地化字符串。
        /// </summary>
        internal static string SQL_Select_FunctionMenu_Ver_001 {
            get {
                return ResourceManager.GetString("SQL_Select_FunctionMenu_Ver_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select UserPassword from User where UserName = ? 的本地化字符串。
        /// </summary>
        internal static string SQL_Select_User_Password_Ver_001 {
            get {
                return ResourceManager.GetString("SQL_Select_User_Password_Ver_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select * from User where UserName = ? 的本地化字符串。
        /// </summary>
        internal static string SQL_Select_User_Ver_001 {
            get {
                return ResourceManager.GetString("SQL_Select_User_Ver_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select * from UserGroup where UserGroupName = ? 的本地化字符串。
        /// </summary>
        internal static string SQL_Select_UserGroup_Ver_001 {
            get {
                return ResourceManager.GetString("SQL_Select_UserGroup_Ver_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select * from UserGroup 的本地化字符串。
        /// </summary>
        internal static string SQL_Select_UserGroupList_Ver_001 {
            get {
                return ResourceManager.GetString("SQL_Select_UserGroupList_Ver_001", resourceCulture);
            }
        }
    }
}
